# Shell variables
# Generated by 'wal'
wallpaper='/home/grace/Downloads/wp/o1350750.jpg'

# Special
background='#ffffff'
foreground='#080707'
cursor='#080707'

# Colors
color0='#ffffff'
color1='#B2B0AF'
color2='#C2BDBB'
color3='#C4C1BF'
color4='#C0BFC0'
color5='#D2D0CF'
color6='#080707'
color7='#080707'
color8='#999999'
color9='#B2B0AF'
color10='#C2BDBB'
color11='#C4C1BF'
color12='#C0BFC0'
color13='#D2D0CF'
color14='#E1DFDE'
color15='#080707'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
